server:
  port: 8076
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8


spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  config:
    activate:
      on-profile: dev
  devtools:
    livereload:
      enabled: true

