server:
  port: 8076
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8


spring:
  config:
    activate:
      on-profile: dev
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  devtools:
    livereload:
      enabled: true
  messages:
    basename: classpath:/messages
    encoding: utf-8
    cache-duration: 3
